# This is the config file for NwmToShef.py
# YAML Format

user_agent_pre : 'NOAA NWS'
rfc_id : 'NW'
nomads_rfc_url : 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/post-processed/RFC/'
nwm_type : 'channel_rt' # domain type: channel_rt, fe (forcings engine), land, shapefile
nwm_var : 'streamflow'
NWPSapi:          "https://api.water.noaa.gov/nwps/v1/"
outputFileName:   nwm_nc_pts_                # need to add  timestamp options.  On the ldad:  /data/Incoming

#####Output file header lines, comment out/remove empty lines####
outputFileHeaderLines:
  line1: "TTAA00 KPTR @@@@@@"                                         #  @@@@@@ replaced with DDHHMM  (product timestamp)
  line2: "NWM_webNc"                                                            #blank line
  line3: ": SHEF encoded NWM guidance for <MODTYPE>"  
  line4: ": Data retrieved from NWM data services at <TIMESTAMP>"       #  <TIMESTAMP> gets replaced with a current date/time
  
####List of NWM forecasts to request and default PEDTS code for shef data####
nwm_var_meta:
#  analysis_assim: 
#    streamflowflow  : "QRIFU"
  short_range: 
     streamflow   : "QRIFM"  # for total water level, this as FM
#  medirum_range: 
#    streamflow   :  "QRIFRZM"  # for total water level, this is FR
#  long_range: 
#    streamflow   :  "QRIFXZM"
  medium_range_blend: 
    streamflow   :  "QRIFXZM"  # for total water level, this is FR
    
#####List of NWS sites to ingest with Default PEDTS Code####
sites : [
  wsri1,
  alrw1,
  aplo3,
  arai1,
  ardw1,
  arki1,
  atgw1,
  beao3,
  bero3,
  bfkw4,
  #bmtw1, tidal
  bonm8,
  bono3,
  brfi1,
  brni1,
  btsi1,
  cabi1,
  calw1,
  cami1,
  cfmm8,
  chto3,
  ciyw1,
  cldi1,
  clfw1,
  cokw1,
  coto3,
  crnz1,
  cshw1,
  ctho3,
  darm8,
  dedi1,
  deeo3,
  dggi1,
  dlgm8,
  dono3,
  drmm8,
  drsw1,
  dsrw1,
  dwri1,
  easi1,
  #ebsw1, tidal
  ecdo3,
  egco3,
  elko3,
  elww1,
  envi1,
  falo3,
  fcfm8,
  ffxw1,
  fism8,
  flgw4,
  fsso3,
  garw1,
  gibo3,
  gorw1,
  grew4,
  grrw1,
  hcro3,
  hhwm8,
  imno3,
  ipdi1,
  issw1,
  jhno3,
  kbdm8,
  kerm8,
  krbo3,
  lauw1,
  leri1,
  lndw1,
  loci1,
  lopo3,
  loso3,
  lsdw1,
  lsto3,
  lydm8,
  mado3,
  mfdo3,
  mfnw1,
  midi1,
  mlbo3,
  mlkw1,
  mnsw1,
  mono3,
  mori1,
  morw1,
  mplo3,
  myko3,
  myno3,
  nasw1,
  #nffq2, canada
  nfnw1,
  nisw1,
  nitw1,
  nspw1,
  nssw1,
  ocho3,
  oknw1,
  orfi1,
  ortw1,
  paci1,
  pacw1,
  pacw4,
  phio3,
  pilw1,
  pldi1,
  ploi1,
  powo3,
  prci1,
  prcm8,
  prii1,
  prli1,
  pulw1,
  rccm8,
  rigi1,
  rodw1,
  salw4,
  sati1,
  satw1,
  scoo3,
  scro3,
  seli1,
  sfcm8,
  sfln2,
  shaw1,
  silo3,
  skow1,
  slkw1,
  sltw1,
  smni1,
  smrw1,
  snqw1,
  spew1,
  spro3,
  srlm8,
  srmo3,
  srmw1,
  ssuw1,
  sthw1,
  stii1,
  strm8,
  suvo3,
  swrm8,
  tanw1,
  tchw1,
  tdao3,
  thnw1,
  thrm8,
  tido3,
  tilo3,
  tilw1,
  tlmo3,
  tlrw1,
  tlyo3,
  tnaw1,
  tolw1,
  topi1,
  trao3,
  trso3,
  trym8,
  ubdw1,
  undw1,
  veno3,
  wchw1,
  wdhn2,
  wfbm8,
  wgcm8,
  whrm8,
  wilw1,
  wydw1
]


#####List of NWS sites to ingest with Custom PEDTS Codes####

customSites : [WLUH1]




  
