# This is the config file for NwmToShef.py
# YAML Format

user_agent_pre : 'NOAA NWS'
rfc_id : 'NW'
nomads_nwm_url : 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/'
nwm_type : 'channel_rt' # domain type: channel_rt, fe (forcings engine), land, shapefile
nwm_var : 'streamflow'
NWPSapi:          "https://api.water.noaa.gov/nwps/v1/"
outputFileName:   LDAD-SHEF-nwm_nc_pts # adding nwm_var_meta and .shef as suffix defined more in script area

#####Output file header lines, comment out/remove empty lines####
outputFileHeaderLines:
  line1: "TTAA00 KPTR @@@@@@"                                         #  @@@@@@ replaced with DDHHMM  (product timestamp)
  line2: "NWM_webNc"                                                            #blank line
  line3: ": SHEF encoded NWM guidance for <MODTYPE>"  
  line4: ": Data retrieved from NWM data services at <TIMESTAMP>"       #  <TIMESTAMP> gets replaced with a current date/time
  
####List of NWM forecasts to request and default PEDTS code for shef data####
nwm_version_var_meta:
  oper:
  #  analysis_assim: 
  #    streamflow : "QRIFUZ"
    short_range: 
      streamflow   : "QRIFMZ"  # for total water level, this as FM, was missing extremum
  #  medirum_range: 
  #    streamflow   :  "QRIFRZM"  # for total water level, this is FR
  #  long_range: 
  #    streamflow   :  "QRIFXZM"
    medium_range_blend: 
      streamflow   :  "QRIFXZM"  # for total water level, this is FR
  para:
    short_range: 
      streamflow : "QRIFNZ"  # for total water level, this as FM, was missing extremum
    medium_range_blend: 
      streamflow : "QRIFVZM"  # for total water level, this is FR

    
#####List of NWS sites to ingest with Default PEDTS Code####
sites : [
 ABOM8,
 AFRI1,
 AGNO3,
 ALBO3,
 ALFW1,
 ALPW4,
 ALRW1,
 AMFI1,
 ANAW1,
 ANTI1,
 APLO3,
 APRO3,
 ARAI1,
 #ARDQ2,
 ARDW1,
 ARGW1,
 ARKI1,
 ARLW1,
 ARWO3,
 ASTO3,
 AUBW1,
 AURO3,
 BCDW1,
 BCLO3,
 BDDI1,
 BEAO3,
 BELM8,
 BERO3,
 BEUO3,
 BFEI1,
 BFKW4,
 BFTI1,
 BIGI1,
 #BIRQ2,
 BITM8,
 BLUO3,
 BONM8,
 BONO3,
 BRFI1,
 BRNI1,
 BTSI1,
 BULO3,
 BUMW1,
 BUSO3,
 BWKI1,
 BWMI1,
 CABI1,
 CALW1,
 CAMI1,
 CANO3,
 CASW1,
 CBAO3,
 CENW1,
 CFMM8,
 CGMW1,
 CGRO3,
 #CHAO3, error - tidal
 CHDW1,
 CHEI1,
 CHJW1,
 CHTO3,
 CIYW1,
 CLDI1,
 CLEW1,
 CLFW1,
 #CLUW1, error - perhaps multi-lid per reservoir issue?
 COCO3,
 COEI1,
 COKW1,
 CONW1,
 COQO3,
 CORO3,
 COTO3,
 CRNW1,
 CRPW1,
 CSDI1,
 CTAW1,
 CTLI1,
 CWMO3,
 DARM8,
 #DCDQ2,
 DEDI1,
 DEEO3,
 DETO3,
 DGGI1,
 DLGM8,
 DLLO3,
 DONO3,
 #DORO3, empty
 DOTW1,
 DRBI1,
 DRMM8,
 DRSW1,
 DSRW1,
 DWRI1,
 EASI1,
 EASW1,
 ECDO3,
 EGCO3,
 EGLO3,
 EKTO3,
 ELKO3,
 ELWW1,
 EMMI1,
 ENVI1,
 ESTO3,
 #EUGO3, empty
 FALO3,
 FCFM8,
 FFXW1,
 FISM8,
 FLGW4,
 FOSO3,
 FPOM8,
 FRMO3,
 FRNO3,
 FRYW1,
 FSSO3,
 GARW1,
 GCDW1,
 GIBO3,
 GLBW1,
 GORW1,
 GOSO3,
 GPRO3,
 GRAO3,
 GREW4,
 GSVO3,
 GVZW4,
 HAGW1,
 HAHW1,
 HALI1,
 HARO3,
 HCDI1,
 HCRO3,
 HEII1,
 #HHDW1, empty
 HHWM8,
 HLKW1,
 HODO3,
 HOPI1,
 HOPW1,
 HOTI1,
 HRSI1,
 HWRI1,
 #IHDW1, error
 IMNO3,
 IPDI1,
 ISLI1,
 ISSW1,
 JASO3,
 #JDAO3, error
 JFFO3,
 JHNO3,
 JKSW4,
 JLKW4,
 KACW1,
 #KADW1, error
 KBDM8,
 #KEDW1, error
 KEEW1,
 KELW1,
 KERM8,
 KIOW1,
 #KLMW1, empty
 KRBO3,
 KTFW1,
 LAUW1,
 LEOI1,
 LERI1,
 LGDW1,
 LGNO3,
 #LGRW1, error
 LGSW1,
 LLKW1,
 #LMNW1, error
 LNDW1,
 LOCI1,
 LOPO3,
 LOPW1,
 LRWW1,
 LSDW1,
 LSMO3,
 LSTO3,
 LUCI1,
 LWRI1,
 LYDM8,
 MADO3,
 MAKI1,
 MAYW1,
 #MCDQ2,
 MCMO3,
 #MCMW1, error
 MCZO3,
 MEHO3,
 MFDO3,
 MFNW1,
 MFPI1,
 MIDI1,
 MILI1,
 #MKDO3, error
 MKNW1,
 MLBO3,
 MLKW1,
 MMRW1,
 MNRO3,
 MNSW1,
 MODO3,
 MONO3,
 MORI1,
 MORW1,
 MPLO3,
 MROW1,
 #MSRW1, error
 MVEW1,
 #MYDW1, error
 MYKO3,
 MYNO3,
 MYPO3,
 NACW1,
 NASW1,
 NEWW1,
 #NFFQ2,
 NFNW1,
 NISW1,
 NITW1,
 NKSW1,
 #NOXM8, error
 NRKW1,
 NSPW1,
 NSSW1,
 #OCDO3, error
 OCUO3,
 OGCN2,
 OKMW1,
 OKNW1,
 OMCN2,
 ORCO3,
 ORFI1,
 ORTW1,
 #OWCO3, error
 OWYO3,
 PACI1,
 PACW1,
 PACW4,
 PALI1,
 PARI1,
 PARW1,
 PATW1,
 PDTO3,
 PERM8,
 PESW1,
 PHIO3,
 PIHI1,
 PILW1,
 PITW1,
 PLDI1,
 PLNM8,
 PLOI1,
 PORI1,
 POWO3,
 PRCI1,
 PRCM8,
 PRDW1,
 PRII1,
 PRLI1,
 PRPI1,
 PRTI1,
 PRTO3,
 PRVO3,
 #PRWW1, error
 PULW1,
 PUYW1,
 #PVDO3, error
 PWDO3,
 #QBYQ2,
 RAWW1,
 RCCM8,
 RDLO3,
 REEO3,
 #REVQ2,
 REXI1,
 RIDI1,
 RIGI1,
 #RIMW1, error
 RISW1,
 RNTW1,
 RODW1,
 RRHW1,
 RSBO3,
 RYGO3,
 SAKW1,
 SALW4,
 SATI1,
 SATW1,
 #SCDO3, error
 SCOO3,
 SCRO3,
 SELI1,
 SERO3,
 SFCM8,
 SFLN2,
 SHAW1,
 #SHDW1, error
 SHNO3,
 SHYI1,
 SIFI1,
 SILO3,
 SJMI1,
 SKAW1,
 #SKBW1, error
 SKOW1,
 SKRW1,
 #SLCQ2,
 SLKW1,
 SLMO3,
 SLTW1,
 #SMKQ2,
 SMNI1,
 SMRW1,
 SNAI1,
 SNAW1,
 SNDO3,
 SNQW1,
 SNYI1,
 SPDI1,
 SPEW1,
 SPOW1,
 SPRO3,
 SQUW1,
 SRCW1,
 SRGM8,
 SRLM8,
 SRMO3,
 SRMW1,
 SSFW1,
 SSUW1,
 STHW1,
 STII1,
 STRM8,
 SUVO3,
 SWAI1,
 SWRM8,
 SYCO3,
 TANW1,
 TCHW1,
 TDAO3,
 TEAI1,
 THNW1,
 THRM8,
 TIDO3,
 TILO3,
 TILW1,
 TLMO3,
 TLRW1,
 TLYO3,
 TNAW1,
 TOLW1,
 TONW1,
 TOPI1,
 TOTW1,
 TRAO3,
 TRBO3,
 TRSO3,
 TRYM8,
 TRYO3,
 UBDW1,
 UMAO3,
 UMTW1,
 UNDW1,
 UNYO3,
 VALO3,
 VAPW1,
 VENO3,
 VICM8,
 VIDO3,
 WANW1,
 WARO3,
 WAUO3,
 WCHW1,
 WEII1,
 WELW1,
 WFBM8,
 WGCM8,
 WHBI1,
 WHRM8,
 WILW1,
 WLAO3,
 #WLSO3, error
 WNRO3,
 WODI1,
 WRAW1,
 WRMO3,
 WSLO3,
 WSNO3,
 WSRI1,
 WTHW1,
 WTLO3,
 WYDW1
]


#####List of NWS sites to ingest with Custom PEDTS Codes####

customSites : [WLUH1]




  
